### ISSUE TITLE
Crash when specifying mod blocks for custom cobblework

### ISSUE THREAD

**Issue by Fenfalleen** [CobbleWorksMC/CobbleWorks#4]
[crash-2017-08-17_00.24.29-client.txt](https://github.com/CobbleWorksMC/CobbleWorks/files/1230246/crash-2017-08-17_00.24.29-client.txt)

[Custom_Cobblegen.txt](https://github.com/CobbleWorksMC/CobbleWorks/files/1230248/Custom_Cobblegen.txt)

If I replace all of the blocks from mods with normal minecraft blocks, it works just fine.

Apologies in advance if I just did not do it correctly.

**Comment by CobbleWorksMC** [comment]
Many modded blocks and items use the same registry name for many items / blocks, differentiating them by metadata. This looks to be a case of something expecting to have a metadata value, but not getting one.

If you specify items or blocks that need a metadata value, then you need to put that in the config file aswell. Load into the game with the Custom CW disabled, and use the F3 + H overlay to find the exact name and metadata of any items / blocks you use. Someday I'll update the config to specify that.

Either that or the CCW is horribly broken and somehow slipped through the update. I'll give the code a solid look through while you investigate the metadata thing on your end.

**Comment by CobbleWorksMC** [comment]
Scratch that, I found the issue.

I added a flag that trips when the Custom CW detects improper configurations, which makes the block not register on launch. I forgot to check this flag when registering the block renderer, which caused a null pointer exception.

If you want more help fixing your config, please post your fml log for the launch where this crash occured, and I will help point out where it tells you what block / item did not register properly, and how to fix it.

**Comment by Fenfalleen** [comment]
[crash-2017-08-17_18.06.39-client.txt](https://github.com/CobbleWorksMC/CobbleWorks/files/1232858/crash-2017-08-17_18.06.39-client.txt)
[Custom_Cobblegen.txt](https://github.com/CobbleWorksMC/CobbleWorks/files/1232856/Custom_Cobblegen.txt)
[fml-client-latest.txt](https://github.com/CobbleWorksMC/CobbleWorks/files/1232857/fml-client-latest.txt)


Thank you so much. I really enjoy this mod and hope this can save other people from the same issue!

My metadatas appeared to be correct, as far as I could tell.


Here are the copies of the custom config, crash report, and forge logs to assure they're the same.

**Comment by CobbleWorksMC** [comment]
Ok, based on the log you posted, it would appear that chancecubes:chance_cube failed to register to the Custom CW (line 1740). I'm not super familliar with the chance cubes mod, but from what I've heard about it, the item you're trying to register probably has some sort of metadata or NBT tag associated with it.

The new version of CW, published earlier today, has an update that fixes metadata integration with CCW items. To use it, simply add a comma then the metadata value after the item ID in the CCW config file. NBT tags are not yet supported, but I plan on integrating them at some point in the future.

Additionally, this update fixed one other crash, unrelated to this issue. I recommend updating whenever you can.

Edit: This might be a mod loading order issue. I'll try a different fix and see if it works, if it does, then there will be another update today.

**Comment by CobbleWorksMC** [comment]
Try version 2.2.1, as I suspected, Chance Cubes loaded its items after Cobbleworks, so checking their items while registering the CCW returned that there was no such thing as a chancecubes:chance_cube.

I blame legacy code from the 1.10 version xd

**Comment by Fenfalleen** [comment]
Yep, the updated version works!

Thank you so much for your timely assistance and your mod! I'll enjoy using it so much in the future!!

:)

**Comment by Fenfalleen** [comment]
While I've got your attention: when the RF costs of generation are above the internal buffer of the Custom Gen, it stops functioning!

**Comment by CobbleWorksMC** [comment]
Well shit, I really never expected anyone to actually try to balance the block. I guess I should make the max RF the blocks hold a configurable value.
I'll do that tomorrow. For now, enjoy the 1m^3 of pure balance you've created.

**Comment by CobbleWorksMC** [comment]
Alright, version 2.3 is uploaded and should be public in a few minutes.

I future proofed this version a little, not only are the RF capacities of each block now configurable, but also the lava capacities are aswell. If you encounter any other problems, please do not hesitate to point them out.

**Comment by Fenfalleen** [comment]
Thank you so much! Congrats on the work and I hope to use this for the rest of my crafting days! :)

**Comment by Fenfalleen** [comment]
Actually there still is a little bit of a hitch: even though you can specify an amount of rf for the internal buffer, the in-game machine uses the default amount and the same problems occur.

**Comment by Fenfalleen** [comment]
In fact, it doesn't register that the lava values are set to 0 either.

**Comment by CobbleWorksMC** [comment]
Sorry for the late response, while fixing this bug I discovered another one that is giving me a little more trouble than I expected. While I'm fixing that, let me see if I understand your issue completely, so I know exactly what to fix.

On your end, the amount of RF the block holds is not accurate? Because that function is working on my end.
Or is it the RF/t values that are bugged?
The lava capacity works fine on my end, however the lava/t values aren't functioning properly, and I'm fixing that now.

**Comment by CobbleWorksMC** [comment]
I pushed an update to fix the other errors that have come to my attention, it should be live in a few minutes. It contains a potential fix for this problem, let me know if it finally works out for you.

**Comment by Fenfalleen** [comment]
Sorry about being so late. I just got a new ISP to install and it's been very hectic;

It is no longer asking for lava, but the internal RF values still don't register.

**Comment by CobbleWorksMC** [comment]
Yeah, I've been slow on the updates lately because classes started last week for me.
Going off your config, it not asking for lava seems to be working, however in my test environment, both the configurations for RF capacity and RF/t values function as intended.

**Comment by Fenfalleen** [comment]
I even tried removing the config and using the default, just to see, and the in-game buffer is only 250,000, though the file states it should be 1 mil.
